name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag apache-sample-hit:$(date +%s)

    - uses: docker/login-action@v2.0.0
    - name: Docker Login
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        # Username used to log against the Docker registry
        username: hitanshu91
        # Password or personal access token used to log against the Docker registry
        password: <password>
